import { z } from 'zod';
export const idParamsSchema = z.object({ id: z.string().cuid() });
export const listQuerySchema = z.object({ page: z.coerce.number().int().min(1).default(1), limit: z.coerce.number().int().min(1).max(100).default(20), search: z.string().trim().max(100).optional(), status: z.enum(['active', 'inactive']).optional(), sortOrder: z.enum(['asc', 'desc']).default('desc') });
const namedMaster = z.object({ name: z.string().trim().min(2).max(120), slug: z.string().trim().toLowerCase().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/), description: z.string().trim().max(1000).nullish(), isActive: z.boolean().default(true) });
export const categoryCreateSchema = namedMaster; export const categoryUpdateSchema = namedMaster.partial();
export const subCategoryCreateSchema = namedMaster.extend({ categoryId: z.string().cuid() }); export const subCategoryUpdateSchema = subCategoryCreateSchema.partial();
export const brandCreateSchema = namedMaster.extend({ logoUrl: z.string().url().nullish() }); export const brandUpdateSchema = brandCreateSchema.partial();
export const unitCreateSchema = z.object({ name: z.string().trim().min(2).max(60), shortName: z.string().trim().min(1).max(12), decimalAllowed: z.boolean().default(false), isActive: z.boolean().default(true) }); export const unitUpdateSchema = unitCreateSchema.partial();
const money = z.string().regex(/^\d+(?:\.\d{1,2})?$/);
const productShape = { name: z.string().trim().min(2).max(180), slug: z.string().trim().toLowerCase().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/), sku: z.string().trim().min(1).max(80), barcode: z.string().trim().max(100).nullish(), categoryId: z.string().cuid(), subCategoryId: z.string().cuid().nullish(), brandId: z.string().cuid().nullish(), unitId: z.string().cuid(), description: z.string().trim().max(5000).nullish(), purchasePrice: money, salePrice: money, dealerPrice: money.nullish(), minimumSalePrice: money.nullish(), trackStock: z.boolean().default(true), serialized: z.boolean().default(false), reorderLevel: z.string().regex(/^\d+(?:\.\d{1,3})?$/).default('0'), allowNegativeStock: z.boolean().default(false), warrantyEnabled: z.boolean().default(false), warrantyDuration: z.number().int().positive().nullish(), warrantyUnit: z.enum(['DAYS', 'MONTHS', 'YEARS']).nullish(), primaryImageUrl: z.string().url().nullish(), isActive: z.boolean().default(true) };
function rules(value: z.infer<z.ZodObject<typeof productShape>>, context: z.RefinementCtx) { if (value.serialized && !value.trackStock) context.addIssue({ code: 'custom', path: ['trackStock'], message: 'Serialized products must track stock.' }); if (value.minimumSalePrice && Number(value.minimumSalePrice) > Number(value.salePrice)) context.addIssue({ code: 'custom', path: ['minimumSalePrice'], message: 'Minimum sale price cannot exceed sale price.' }); if (value.warrantyEnabled && (!value.warrantyDuration || !value.warrantyUnit)) context.addIssue({ code: 'custom', path: ['warrantyDuration'], message: 'Warranty duration and unit are required.' }); }
export const productCreateSchema = z.object(productShape).superRefine(rules);
export const productUpdateSchema = z.object(productShape).partial().superRefine((value, context) => {
  if (value.serialized === true && value.trackStock === false) context.addIssue({ code: 'custom', path: ['trackStock'], message: 'Serialized products must track stock.' });
  if (value.minimumSalePrice && value.salePrice && Number(value.minimumSalePrice) > Number(value.salePrice)) context.addIssue({ code: 'custom', path: ['minimumSalePrice'], message: 'Minimum sale price cannot exceed sale price.' });
  if (value.warrantyEnabled === true && (!value.warrantyDuration || !value.warrantyUnit)) context.addIssue({ code: 'custom', path: ['warrantyDuration'], message: 'Warranty duration and unit are required.' });
});
export const productListQuerySchema = listQuerySchema.extend({ category: z.string().cuid().optional(), subCategory: z.string().cuid().optional(), brand: z.string().cuid().optional(), serialized: z.enum(['true', 'false']).optional(), lowStock: z.enum(['true', 'false']).optional(), sortBy: z.enum(['name', 'sku', 'createdAt', 'salePrice']).default('createdAt') });
