CREATE TYPE "StockMovementType" AS ENUM ('OPENING_STOCK','PURCHASE','PURCHASE_RETURN','SALE','SALE_RETURN','ADJUSTMENT_IN','ADJUSTMENT_OUT','DAMAGE','TRANSFER_IN','TRANSFER_OUT');
CREATE TYPE "StockAdjustmentReason" AS ENUM ('OPENING_BALANCE','PHYSICAL_COUNT','DAMAGE_CORRECTION','LOST','FOUND','DATA_CORRECTION','OTHER');
CREATE TYPE "SerialStatus" AS ENUM ('IN_STOCK','RESERVED','SOLD','RETURNED','DAMAGED','IN_RMA','SENT_TO_SUPPLIER','RECEIVED_FROM_SUPPLIER','DELIVERED_TO_CUSTOMER','SCRAPPED');

CREATE TABLE "Warehouse" ("id" TEXT NOT NULL,"businessId" TEXT NOT NULL,"name" TEXT NOT NULL,"code" TEXT NOT NULL,"description" TEXT,"address" TEXT,"isDefault" BOOLEAN NOT NULL DEFAULT false,"isActive" BOOLEAN NOT NULL DEFAULT true,"createdById" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Warehouse_pkey" PRIMARY KEY ("id"));
CREATE TABLE "StockMovement" ("id" TEXT NOT NULL,"businessId" TEXT NOT NULL,"warehouseId" TEXT NOT NULL,"productId" TEXT NOT NULL,"type" "StockMovementType" NOT NULL,"quantity" DECIMAL(18,3) NOT NULL,"referenceType" TEXT,"referenceId" TEXT,"unitCost" DECIMAL(18,2),"note" TEXT,"occurredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"createdById" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "StockMovement_pkey" PRIMARY KEY ("id"));
CREATE TABLE "StockBalance" ("id" TEXT NOT NULL,"businessId" TEXT NOT NULL,"warehouseId" TEXT NOT NULL,"productId" TEXT NOT NULL,"quantity" DECIMAL(18,3) NOT NULL DEFAULT 0,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "StockBalance_pkey" PRIMARY KEY ("id"));
CREATE TABLE "StockAdjustment" ("id" TEXT NOT NULL,"businessId" TEXT NOT NULL,"warehouseId" TEXT NOT NULL,"reason" "StockAdjustmentReason" NOT NULL,"note" TEXT,"createdById" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "StockAdjustment_pkey" PRIMARY KEY ("id"));
CREATE TABLE "StockAdjustmentLine" ("id" TEXT NOT NULL,"adjustmentId" TEXT NOT NULL,"productId" TEXT NOT NULL,"direction" "StockMovementType" NOT NULL,"quantity" DECIMAL(18,3) NOT NULL,"unitCost" DECIMAL(18,2),CONSTRAINT "StockAdjustmentLine_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SerialItem" ("id" TEXT NOT NULL,"businessId" TEXT NOT NULL,"warehouseId" TEXT NOT NULL,"productId" TEXT NOT NULL,"serialNumber" TEXT NOT NULL,"status" "SerialStatus" NOT NULL DEFAULT 'IN_STOCK',"purchaseId" TEXT,"saleId" TEXT,"customerId" TEXT,"supplierId" TEXT,"warrantyStart" TIMESTAMP(3),"warrantyEnd" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "SerialItem_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "Warehouse_businessId_code_key" ON "Warehouse"("businessId","code"); CREATE INDEX "Warehouse_businessId_isActive_idx" ON "Warehouse"("businessId","isActive"); CREATE INDEX "Warehouse_businessId_isDefault_idx" ON "Warehouse"("businessId","isDefault");
CREATE INDEX "StockMovement_businessId_productId_idx" ON "StockMovement"("businessId","productId"); CREATE INDEX "StockMovement_businessId_warehouseId_idx" ON "StockMovement"("businessId","warehouseId"); CREATE INDEX "StockMovement_businessId_productId_warehouseId_idx" ON "StockMovement"("businessId","productId","warehouseId"); CREATE INDEX "StockMovement_businessId_occurredAt_idx" ON "StockMovement"("businessId","occurredAt"); CREATE INDEX "StockMovement_referenceType_referenceId_idx" ON "StockMovement"("referenceType","referenceId");
CREATE UNIQUE INDEX "StockBalance_businessId_warehouseId_productId_key" ON "StockBalance"("businessId","warehouseId","productId"); CREATE INDEX "StockBalance_businessId_productId_idx" ON "StockBalance"("businessId","productId"); CREATE INDEX "StockBalance_businessId_warehouseId_idx" ON "StockBalance"("businessId","warehouseId");
CREATE INDEX "StockAdjustment_businessId_createdAt_idx" ON "StockAdjustment"("businessId","createdAt"); CREATE INDEX "StockAdjustment_businessId_warehouseId_idx" ON "StockAdjustment"("businessId","warehouseId"); CREATE INDEX "StockAdjustmentLine_adjustmentId_idx" ON "StockAdjustmentLine"("adjustmentId"); CREATE INDEX "StockAdjustmentLine_productId_idx" ON "StockAdjustmentLine"("productId");
CREATE UNIQUE INDEX "SerialItem_businessId_serialNumber_key" ON "SerialItem"("businessId","serialNumber"); CREATE INDEX "SerialItem_businessId_productId_idx" ON "SerialItem"("businessId","productId"); CREATE INDEX "SerialItem_businessId_warehouseId_idx" ON "SerialItem"("businessId","warehouseId"); CREATE INDEX "SerialItem_businessId_status_idx" ON "SerialItem"("businessId","status");

ALTER TABLE "Warehouse" ADD CONSTRAINT "Warehouse_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "Warehouse" ADD CONSTRAINT "Warehouse_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "StockMovement" ADD CONSTRAINT "StockMovement_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "StockMovement" ADD CONSTRAINT "StockMovement_warehouseId_fkey" FOREIGN KEY ("warehouseId") REFERENCES "Warehouse"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "StockMovement" ADD CONSTRAINT "StockMovement_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "StockMovement" ADD CONSTRAINT "StockMovement_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "StockBalance" ADD CONSTRAINT "StockBalance_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "StockBalance" ADD CONSTRAINT "StockBalance_warehouseId_fkey" FOREIGN KEY ("warehouseId") REFERENCES "Warehouse"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "StockBalance" ADD CONSTRAINT "StockBalance_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "StockAdjustment" ADD CONSTRAINT "StockAdjustment_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "StockAdjustment" ADD CONSTRAINT "StockAdjustment_warehouseId_fkey" FOREIGN KEY ("warehouseId") REFERENCES "Warehouse"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "StockAdjustment" ADD CONSTRAINT "StockAdjustment_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "StockAdjustmentLine" ADD CONSTRAINT "StockAdjustmentLine_adjustmentId_fkey" FOREIGN KEY ("adjustmentId") REFERENCES "StockAdjustment"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "StockAdjustmentLine" ADD CONSTRAINT "StockAdjustmentLine_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SerialItem" ADD CONSTRAINT "SerialItem_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "SerialItem" ADD CONSTRAINT "SerialItem_warehouseId_fkey" FOREIGN KEY ("warehouseId") REFERENCES "Warehouse"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "SerialItem" ADD CONSTRAINT "SerialItem_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
