export const demoCustomers = [
  {
    name: 'Rahman Computers',
    phone: '01712 345 678',
    district: 'Dhaka',
    type: 'Dealer',
    balance: 48500,
    status: 'Active',
  },
  {
    name: 'Nabila Enterprise',
    phone: '01819 882 104',
    district: 'Chattogram',
    type: 'Retail',
    balance: 0,
    status: 'Active',
  },
  {
    name: 'Digital Point BD',
    phone: '01670 133 902',
    district: 'Sylhet',
    type: 'Corporate',
    balance: 76200,
    status: 'Active',
  },
  {
    name: 'Walk-in customer',
    phone: '—',
    district: 'Dhaka',
    type: 'Retail',
    balance: 0,
    status: 'Active',
  },
];
export const demoSuppliers = [
  {
    name: 'Tech Distribution Ltd',
    phone: '02 889 4200',
    district: 'Dhaka',
    purchases: '৳8,42,000',
    payable: 118000,
    status: 'Active',
  },
  {
    name: 'Mobile Source BD',
    phone: '01844 820 311',
    district: 'Dhaka',
    purchases: '৳4,16,500',
    payable: 0,
    status: 'Active',
  },
  {
    name: 'Global Components',
    phone: '01730 992 001',
    district: 'Chattogram',
    purchases: '৳2,76,800',
    payable: 18500,
    status: 'Active',
  },
];
export const demoProducts = [
  {
    product: 'Lenovo ThinkPad E14 Gen 5',
    sku: 'LEN-E14-G5',
    category: 'Laptop',
    stock: 12,
    price: 98500,
    status: 'In stock',
  },
  {
    product: 'Samsung Galaxy A55 5G',
    sku: 'SAM-A55-256',
    category: 'Mobile',
    stock: 8,
    price: 52999,
    status: 'Low stock',
  },
  {
    product: 'Logitech MX Master 3S',
    sku: 'LOG-MX3S',
    category: 'Accessories',
    stock: 31,
    price: 12400,
    status: 'In stock',
  },
  {
    product: 'HP LaserJet M211dw',
    sku: 'HP-M211DW',
    category: 'Printer',
    stock: 0,
    price: 24500,
    status: 'Out of stock',
  },
];
