export const inventoryStock = [
  {
    productId: 'demo-product-1',
    product: 'Lenovo ThinkPad E14 Gen 5',
    sku: 'LEN-E14-G5',
    category: 'Laptop',
    brand: 'Lenovo',
    warehouse: 'Main Warehouse',
    quantity: 12,
    reorderLevel: 5,
    status: 'IN_STOCK',
    serialized: true,
  },
  {
    productId: 'demo-product-2',
    product: 'Samsung Galaxy A55 5G',
    sku: 'SAM-A55-256',
    category: 'Mobile',
    brand: 'Samsung',
    warehouse: 'Main Warehouse',
    quantity: 3,
    reorderLevel: 5,
    status: 'LOW_STOCK',
    serialized: true,
  },
  {
    productId: 'demo-product-3',
    product: 'HP LaserJet M211dw',
    sku: 'HP-M211DW',
    category: 'Printer',
    brand: 'HP',
    warehouse: 'Main Warehouse',
    quantity: 0,
    reorderLevel: 2,
    status: 'OUT_OF_STOCK',
    serialized: false,
  },
];
export const inventorySerials = [
  {
    id: 'serial-1',
    serialNumber: 'IMEI-356789012345678',
    product: 'Samsung Galaxy A55 5G',
    sku: 'SAM-A55-256',
    status: 'IN_STOCK',
    warehouse: 'Main Warehouse',
    updatedAt: '26 Aug 2026',
  },
  {
    id: 'serial-2',
    serialNumber: 'PF4A1BC2',
    product: 'Lenovo ThinkPad E14 Gen 5',
    sku: 'LEN-E14-G5',
    status: 'IN_STOCK',
    warehouse: 'Main Warehouse',
    updatedAt: '25 Aug 2026',
  },
];
