import type { Prisma, PrismaClient } from '@prisma/client';

export const BUSINESS_PERMISSIONS = [
  'dashboard.read',
  'customer.read',
  'customer.create',
  'customer.update',
  'customer.delete',
  'supplier.read',
  'supplier.create',
  'supplier.update',
  'supplier.delete',
  'product.create',
  'product.read',
  'product.update',
  'product.delete',
  'category.read',
  'category.create',
  'category.update',
  'category.delete',
  'brand.read',
  'brand.create',
  'brand.update',
  'brand.delete',
  'unit.read',
  'unit.create',
  'unit.update',
  'unit.delete',
  'inventory.read',
  'inventory.adjust',
  'inventory.movement.read',
  'warehouse.read',
  'brand.manage',
  'category.manage',
  'unit.manage',
  'purchase.create',
  'purchase.read',
  'purchase.update',
  'purchase.post',
  'purchase.delete_draft',
  'purchase.return.read',
  'purchase_return.read',
  'purchase_return.create',
  'purchase_return.update',
  'purchase_return.post',
  'purchase_return.delete_draft',
  'sale.create',
  'sale.vat.create',
  'sale.read',
  'sale.update',
  'sale.post',
  'sale.delete_draft',
  'pos.use',
  'sale.return.read',
  'sale_return.read',
  'sale_return.create',
  'sale_return.update',
  'sale_return.post',
  'sale_return.delete_draft',
  'serial.read',
  'warranty.read',
  'warranty.check',
  'rma.read',
  'rma.create',
  'rma.update',
  'rma.inspect',
  'rma.send_supplier',
  'rma.receive_supplier',
  'rma.ready',
  'rma.deliver',
  'rma.cancel',
  'service.create',
  'service.read',
  'service.update',
  'service.diagnose',
  'service.assign',
  'service.approve',
  'service.work',
  'service.ready',
  'service.deliver',
  'service.cancel',
  'report.service',
  'quotation.create',
  'quotation.read',
  'quotation.update',
  'quotation.send',
  'quotation.accept',
  'quotation.reject',
  'quotation.convert',
  'quotation.delete_draft',
  'damage.create',
  'damage.read',
  'damage.update',
  'damage.post',
  'damage.delete_draft',
  'expense.read',
  'expense.type.manage',
  'expense.create',
  'expense.update',
  'expense.post',
  'expense.delete_draft',
  'expense_category.read',
  'expense_category.manage',
  'barcode.generate',
  'financial_account.read',
  'financial_account.create',
  'financial_account.update',
  'financial_account.disable',
  'financial_transaction.read',
  'financial_transaction.create',
  'financial_transaction.post',
  'financial_transfer.read',
  'financial_transfer.create',
  'financial.adjust',
  'accounting.read',
  'accounting.initialize',
  'coa.read',
  'coa.manage',
  'journal.read',
  'journal.create_manual',
  'journal.post',
  'journal.reverse',
  'receivable.read',
  'receivable.receive_payment',
  'payable.read',
  'payable.make_payment',
  'accounting_report.trial_balance',
  'accounting_report.pnl',
  'accounting_report.general_ledger',
  'fiscal_period.read',
  'fiscal_period.manage',
  'fiscal_period.close',
  'cheque.read',
  'investment.read',
  'hr.team.read',
  'team.invite',
  'team.update',
  'team.suspend',
  'team.reactivate',
  'team.revoke_sessions',
  'hr.sales-rep.read',
  'role.read',
  'role.manage',
  'permission.read',
  'approval.read',
  'approval.review',
  'approval.policy.manage',
  'audit.read',
  'report.business',
  'report.sales',
  'report.customer.top',
  'report.customer',
  'report.receivable',
  'report.payable',
  'report.stock.low',
  'report.stock.alert',
  'report.product.sales',
  'report.account.payment',
  'report.expense',
  'report.transaction',
  'report.daily',
  'report.stock',
  'report.stock.list',
  'business.setting.manage',
  'admin.access',
  'marketplace.read',
] as const;

export type BusinessPermission = (typeof BUSINESS_PERMISSIONS)[number];
export type PermissionRisk = 'STANDARD' | 'SENSITIVE' | 'CRITICAL';
const sensitive = new Set<string>([
  'team.suspend',
  'team.revoke_sessions',
  'role.manage',
  'approval.review',
  'approval.policy.manage',
  'journal.reverse',
  'fiscal_period.close',
  'financial.adjust',
]);
const critical = new Set<string>([
  'role.manage',
  'team.suspend',
  'journal.reverse',
  'fiscal_period.close',
]);
export const PERMISSION_REGISTRY = BUSINESS_PERMISSIONS.map((key) => {
  const [module = 'general'] = key.split('.');
  const label = key
    .split('.')
    .map((part) => part.replace(/_/g, ' '))
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' � ');
  return {
    key,
    module,
    label,
    description: `Allows ${label.toLowerCase()} operations within the active business.`,
    risk: critical.has(key) ? 'CRITICAL' : sensitive.has(key) ? 'SENSITIVE' : 'STANDARD',
  };
});
export const DEFAULT_ROLE_NAMES = [
  'OWNER',
  'ADMIN',
  'MANAGER',
  'CASHIER',
  'SALES_REP',
  'ACCOUNTANT',
  'WAREHOUSE_MANAGER',
] as const;
export type DefaultRoleName = (typeof DEFAULT_ROLE_NAMES)[number];
const reporting: BusinessPermission[] = [
  'dashboard.read',
  'report.business',
  'report.sales',
  'report.customer.top',
  'report.customer',
  'report.receivable',
  'report.payable',
  'report.stock.low',
  'report.stock.alert',
  'report.product.sales',
  'report.account.payment',
  'report.expense',
  'report.transaction',
  'report.daily',
  'report.stock',
  'report.stock.list',
];

export const ROLE_PERMISSION_MAP: Record<DefaultRoleName, readonly BusinessPermission[]> = {
  OWNER: BUSINESS_PERMISSIONS,
  ADMIN: BUSINESS_PERMISSIONS,
  MANAGER: BUSINESS_PERMISSIONS.filter(
    (permission) =>
      ![
        'admin.access',
        'business.setting.manage',
        'role.read',
        'role.manage',
        'team.suspend',
        'team.revoke_sessions',
        'approval.policy.manage',
        'approval.review',
        'audit.read',
        'marketplace.read',
        'financial.adjust',
        'financial_account.disable',
        'accounting.initialize',
        'coa.manage',
        'journal.create_manual',
        'journal.post',
        'journal.reverse',
        'receivable.receive_payment',
        'payable.make_payment',
        'fiscal_period.manage',
        'fiscal_period.close',
      ].includes(permission),
  ),
  CASHIER: [
    'dashboard.read',
    'customer.read',
    'product.read',
    'sale.create',
    'sale.vat.create',
    'sale.read',
    'sale.update',
    'sale.post',
    'sale.delete_draft',
    'pos.use',
    'sale.return.read',
    'sale_return.read',
    'sale_return.create',
    'sale_return.update',
    'sale_return.post',
    'sale_return.delete_draft',
    'serial.read',
    'warranty.read',
    'warranty.check',
    'rma.read',
    'rma.create',
    'quotation.create',
    'quotation.read',
    'quotation.update',
    'quotation.send',
    'service.create',
    'service.read',
    'service.deliver',
    'barcode.generate',
    'financial_account.read',
    'financial_transaction.read',
    'financial_transaction.create',
    'receivable.read',
    'receivable.receive_payment',
    'report.daily',
  ],
  SALES_REP: [
    'dashboard.read',
    'customer.read',
    'product.read',
    'sale.create',
    'sale.read',
    'sale.update',
    'sale.post',
    'pos.use',
    'serial.read',
    'warranty.read',
    'warranty.check',
    'quotation.create',
    'quotation.read',
    'quotation.update',
    'quotation.send',
    'quotation.accept',
    'quotation.convert',
  ],
  ACCOUNTANT: [
    'dashboard.read',
    'customer.read',
    'supplier.read',
    'purchase.read',
    'purchase.return.read',
    'purchase_return.read',
    'sale.read',
    'sale.return.read',
    'sale_return.read',
    'expense.read',
    'expense.type.manage',
    'expense.create',
    'expense.update',
    'expense.post',
    'expense.delete_draft',
    'expense_category.read',
    'expense_category.manage',
    'financial_account.read',
    'financial_account.create',
    'financial_account.update',
    'financial_account.disable',
    'financial_transaction.read',
    'financial_transaction.create',
    'financial_transaction.post',
    'financial_transfer.read',
    'financial_transfer.create',
    'financial.adjust',
    'accounting.read',
    'accounting.initialize',
    'coa.read',
    'coa.manage',
    'journal.read',
    'journal.create_manual',
    'journal.post',
    'journal.reverse',
    'receivable.read',
    'receivable.receive_payment',
    'payable.read',
    'payable.make_payment',
    'accounting_report.trial_balance',
    'accounting_report.pnl',
    'accounting_report.general_ledger',
    'fiscal_period.read',
    'fiscal_period.manage',
    'fiscal_period.close',
    'cheque.read',
    'investment.read',
    ...reporting,
  ],
  WAREHOUSE_MANAGER: [
    'dashboard.read',
    'supplier.read',
    'product.create',
    'product.read',
    'brand.manage',
    'category.manage',
    'unit.manage',
    'purchase.create',
    'purchase.read',
    'purchase.return.read',
    'purchase_return.read',
    'purchase_return.create',
    'purchase_return.update',
    'purchase_return.post',
    'purchase_return.delete_draft',
    'serial.read',
    'warranty.read',
    'warranty.check',
    'rma.read',
    'rma.create',
    'rma.update',
    'rma.inspect',
    'rma.send_supplier',
    'rma.receive_supplier',
    'rma.ready',
    'rma.deliver',
    'rma.cancel',
    'damage.create',
    'damage.read',
    'damage.update',
    'damage.post',
    'damage.delete_draft',
    'barcode.generate',
    'report.stock.low',
    'report.stock.alert',
    'report.stock',
    'report.stock.list',
  ],
};

type DatabaseClient = PrismaClient | Prisma.TransactionClient;

export async function provisionBusinessAccess(client: DatabaseClient, businessId: string) {
  const permissions = await Promise.all(
    BUSINESS_PERMISSIONS.map((key) =>
      client.permission.upsert({
        where: { key },
        update: { description: key },
        create: { key, description: key },
      }),
    ),
  );
  const permissionIds = new Map(permissions.map((permission) => [permission.key, permission.id]));
  const roles = new Map<DefaultRoleName, string>();
  for (const roleName of DEFAULT_ROLE_NAMES) {
    const description = 'Default ' + roleName + ' role';
    const role = await client.role.upsert({
      where: { businessId_name: { businessId, name: roleName } },
      update: { isSystem: true, description },
      create: { businessId, name: roleName, isSystem: true, description },
    });
    roles.set(roleName, role.id);
    const desired = ROLE_PERMISSION_MAP[roleName].map((key) => ({
      roleId: role.id,
      permissionId: permissionIds.get(key)!,
    }));
    await client.rolePermission.deleteMany({
      where: {
        roleId: role.id,
        permissionId: { notIn: desired.map((grant) => grant.permissionId) },
      },
    });
    if (desired.length)
      await client.rolePermission.createMany({ data: desired, skipDuplicates: true });
  }
  return { permissionCount: permissions.length, roles };
}
