export const plans = [
  {
    name: 'Starter',
    monthly: '৳499',
    yearly: '৳4,990',
    users: 'Up to 2 users',
    featured: false,
    description: 'For a single shop moving from notebooks and spreadsheets.',
    features: [
      'Products and inventory',
      'Purchase and sales',
      'Barcode-ready POS',
      '7-day free trial',
    ],
  },
  {
    name: 'Business',
    monthly: '৳999',
    yearly: '৳9,990',
    users: 'Up to 5 users',
    featured: true,
    description: 'For active retail teams needing stronger workflow control.',
    features: [
      'Everything in Starter',
      'Role-based access',
      'VAT sales',
      'Serial and IMEI tracking',
    ],
  },
  {
    name: 'Pro',
    monthly: '৳1,999',
    yearly: '৳19,990',
    users: 'Up to 12 users',
    featured: false,
    description: 'For larger operations with more people and stock movement.',
    features: [
      'Everything in Business',
      'More users',
      'Priority onboarding',
      'Operational reports',
    ],
  },
  {
    name: 'Enterprise',
    monthly: 'Custom',
    yearly: 'Custom',
    users: 'Custom users',
    featured: false,
    description: 'For organizations that need a tailored rollout and support plan.',
    features: [
      'Custom rollout',
      'Dedicated support',
      'Migration planning',
      'Packaging by agreement',
    ],
  },
] as const;
